MOCK_JOBS = [
    {
        "id": 1,
        "file_name": "customers.csv",
        "status": "SUCCESS",
        "instruction": "Find credit card numbers in the notes column and replace them with [CARD].",
        "num_processed": 1200,
        "row_count": 1200,
        "regex_pattern": r"\b\d{4}-\d{4}-\d{4}-\d{4}\b",
        "replacement": "[CARD]",
        "target_columns": ["notes"],
        "changed_row_count": 37,
        "column_headers": ["id", "name", "email", "notes"],
        "preview_rows": [
            {
                "id": 1,
                "name": "Alice",
                "email": "alice@example.com",
                "notes": "Paid with [CARD]",
            },
            {
                "id": 2,
                "name": "Bob",
                "email": "bob@example.com",
                "notes": "No card found",
            },
        ],
    },
    {
        "id": 2,
        "file_name": "orders.xlsx",
        "status": "RUNNING",
        "instruction": "Normalize phone numbers in customer notes.",
        "num_processed": 450,
        "row_count": 2000,
        "regex_pattern": "",
        "replacement": "",
        "target_columns": [],
        "changed_row_count": 0,
        "column_headers": [],
        "preview_rows": [],
    },
    {
        "id": 3,
        "file_name": "bad-file.csv",
        "status": "FAILED",
        "instruction": "Extract all email addresses from comments.",
        "num_processed": 0,
        "row_count": 0,
        "regex_pattern": "",
        "replacement": "",
        "target_columns": [],
        "changed_row_count": 0,
        "column_headers": [],
        "preview_rows": [],
        "error_message": "Could not parse CSV headers.",
    },
]
