# Generated by Django 6.0.6 on 2026-07-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="preview_rows",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
