# Generated by Django 6.0.6 on 2026-07-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_job_preview_rows"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="cancel_requested",
            field=models.BooleanField(default=False),
        ),
    ]
