# Generated by Codex on 2026-07-08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_alter_job_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="changed_row_count",
        ),
    ]
